spring:
  application:
    name: cloud-native-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cloud_native_api}
    username: ${SPRING_DATASOURCE_USERNAME:cloud_native_api}
    password: ${SPRING_DATASOURCE_PASSWORD:cloud_native_api}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
